/**
 * pi-workflows — parent-death guard for sub-agent subprocesses (slice 6).
 *
 * Goal: if the parent pi process dies via SIGKILL (or any non-graceful
 * exit), the `pi -p` child must self-terminate so it stops burning
 * Bedrock tokens silently. PRD §5.5.1 specifies a defense-in-depth
 * approach across three layers.
 *
 * **Slice-6 implementation choice.** Of the three options the PRD
 * outlines, slice 6 ships the *universal* layer — a portable
 * `ppid` polling wrapper — as the primary mechanism, because it
 * works identically on Linux, macOS, and any host that has `bash` +
 * `kill`. The Linux-specific `prctl(PR_SET_PDEATHSIG)` path requires
 * a compiled C wrapper which complicates package installation
 * (postinstall + cc availability + glibc-vs-musl ABI). The slice-6
 * acceptance is met by the ppid-poll layer alone; the prctl path is
 * deferred to a follow-up slice and tracked in `parity-gaps.md`.
 *
 * Mechanics. We launch the actual `pi` binary via a tiny generated
 * sh script that:
 *
 *   1. Snapshots its starting `$$` (= the bash pid).
 *   2. Exec-replaces itself with `pi --mode json -p <args…>` in the
 *      foreground so signals propagate.
 *   3. Concurrently, before the exec, starts a watcher subshell that
 *      polls `ppid` of the child every 5 seconds and sends `SIGTERM`
 *      to the child group when the parent reparents to PID 1 (or
 *      otherwise vanishes).
 *
 * The script is generated per-spawn into the run-dir (so it's
 * inspectable for forensics) and deleted on dispatcher cleanup —
 * defensive: if pi crashes between write and exec, the orphan script
 * is harmless.
 *
 * Crash sweep on session_start (PRD §5.8.2) is the secondary safety
 * net: any child that survives both layers is reaped by the manifest
 * comparison there.
 */

import { promises as fs } from "node:fs";
import { join } from "node:path";

import { assertSafeAgentId } from "../util/paths.js";

/**
 * Materialize a parent-death-aware shell wrapper into `<runDir>` and
 * return its absolute path. The wrapper, when executed, launches
 * `command args…` and watches its ppid, killing the launched child
 * when the original parent (`originalParentPid`) is gone.
 *
 * The sh wrapper is **portable** — it relies only on `kill -0` and
 * `sleep`, both POSIX-mandatory.
 */
export async function writeParentDeathWrapper(opts: {
  runDirAbs: string;
  agentId: string;
  originalParentPid: number;
  /** Polling interval in seconds. PRD §5.5.1 says 5s. */
  pollIntervalSeconds?: number;
}): Promise<string> {
  // Defense in depth. Every dispatcher entry point already runs the
  // agentId through `assertSafeAgentId`, but interpolating user-controlled
  // strings into a shell script is the canonical injection footgun —
  // re-validate at the moment of use so a future caller that forgets the
  // upstream validation still gets blocked here.
  assertSafeAgentId(opts.agentId);
  const interval = opts.pollIntervalSeconds ?? 5;
  const path = join(opts.runDirAbs, `.pdeath-${opts.agentId}.sh`);
  // POSIX sh — no bashisms. The wrapper accepts the real command and
  // its args as $@, exec-replaces into them, and starts the watcher
  // in a backgrounded subshell *before* the exec. The watcher
  // captures CHILD_PID via the parent-shell's $$ snapshot, then waits
  // for the parent (pi) to die.
  const script = `#!/bin/sh
# Auto-generated by pi-workflows slice 6 (parent-death guard).
# Run-dir: ${opts.runDirAbs}
# Agent:   ${opts.agentId}
# Original parent pid: ${opts.originalParentPid}
set -eu

PI_PARENT_PID=${opts.originalParentPid}
POLL_INTERVAL=${interval}

# Watcher: poll the original parent's existence; if gone, SIGTERM us.
# We send to $$ which will be the eventual exec'd pi process (since
# exec replaces this shell in-place but keeps the pid).
#
# Critical: redirect watcher's stdio to /dev/null so it doesn't hold
# the spawned-shell's stdout/stderr pipes open after the exec'd child
# closes them — otherwise the parent's stream never sees end.
#
# Loop also exits when the target pid dies so the watcher cleans up
# naturally on graceful child exit.
target_pid=$$
(
  while kill -0 "$PI_PARENT_PID" 2>/dev/null && kill -0 "$target_pid" 2>/dev/null; do
    sleep "$POLL_INTERVAL"
  done
  if ! kill -0 "$PI_PARENT_PID" 2>/dev/null; then
    # Parent gone — give the child SIGTERM. If it ignores SIGTERM
    # for >5s, follow with SIGKILL.
    kill -TERM "$target_pid" 2>/dev/null || true
    sleep 5
    kill -KILL "$target_pid" 2>/dev/null || true
  fi
) </dev/null >/dev/null 2>&1 &

exec "$@"
`;
  await fs.mkdir(opts.runDirAbs, { recursive: true });
  await fs.writeFile(path, script, { mode: 0o700 });
  return path;
}

/**
 * Best-effort removal of a wrapper script after the child exits.
 * Failures are silently ignored — the script is in the run-dir which
 * GC's on its own.
 */
export async function removeParentDeathWrapper(path: string): Promise<void> {
  try {
    await fs.unlink(path);
  } catch {
    // ignore
  }
}
